const teachers = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@eclasslink.edu",
    phone: "+1234567890",
    subject: "Mathematics",
    image: "images/team-6.jpg",
  },
  {
    id: 2,
    name: "Robert Smith",
    email: "robert.smith@eclasslink.edu",
    phone: "+1234567891",
    subject: "Physics",
    image: "images/team-1.jpg",
  },
  {
    id: 3,
    name: "Megan Brown",
    email: "megan.brown@eclasslink.edu",
    phone: "+1234567892",
    subject: "Chemistry",
    image: "images/team-3.jpg",
  },
  {
    id: 4,
    name: "John Doe",
    email: "john.doe@eclasslink.edu",
    phone: "+1234567893",
    subject: "History",
    image: "images/team-2.jpg",
  },
  {
    id: 5,
    name: "Emma Davis",
    email: "emma.davis@eclasslink.edu",
    phone: "+1234567894",
    subject: "Biology",
    image: "images/team-4.jpg",
  },
  {
    id: 6,
    name: "Michael Lee",
    email: "michael.lee@eclasslink.edu",
    phone: "+1234567895",
    subject: "English",
    image: "images/team-5.jpg",
  },
];
export default teachers;
